### PR TITLE
chore!: simplify exports

### PR DESCRIPTION
**Pull request by malinovic**
BREAKING CHANGE: This pull request removes all default exports and enables only named exports for components

### CODE REVIEW

**Review by claudio-OST — CHANGES_REQUESTED** [review]
Good work as always. 

During testing I found that a few stories do not work. The imports in the stories files need to be adjusted: 

import CommentButton from './comment-button';
should be:
import { CommentButton } from './comment-button';

**Comment by malinovic** [comment]
Hi claudio, updated with new changes, please check it out again :)

**Review by claudio-OST — APPROVED** [review]
Everything works now. Great!

**Pull request merged**
